#!/usr/bin/env bash

FG_RED="\033[31m"
FG_GREEN="\033[32m"
FG_BLUE="\033[34m"
RESET="\033[0m"

ask() {
  if [ -n "$1" ]; then
    printf "$1"
    read -p " (y/n): " -n 1
    echo "";

    if [[ $REPLY =~ ^[Yy]$ ]]; then
      return 0;
    fi
  fi

  return 1;
}

link_file() {
  if [ -n "$1" ] && [ -n "$2" ]; then
    home_sub=${2/$HOME/~}
    echo -e "${FG_GREEN}✔${RESET} Linking ${1/$PWD\//} to ${home_sub/$PWD\//}"
    ln -s "$1" "$2"
  fi
}

replace_file() {
  if [ -n "$1" ] && [ -n "$2" ]; then
    if [[ -h "$2" ]]; then
      echo -e "${FG_GREEN}✔${RESET} Unlinking ${2/$HOME/~}"
      unlink "$2"
    else
      echo -e "${FG_GREEN}✔${RESET} Removing ${2/$HOME/~}"
      rm -rf "$2"
    fi

    link_file $1 $2
  fi
}

install_file() {
  if [ -n "$1" ] && [ -n "$2" ]; then
    if [[ -e "$2" ]]; then
      if cmp "$2" "$1" 2>/dev/null; then
        echo -e "${FG_GREEN}✔${RESET} Identical ${1/$PWD\//}"
      else
        if ask "${FG_RED}Overwrite ${2/$HOME/~}?${RESET}"; then
          replace_file "$1" "$2"
        else
          echo -e "${FG_RED}✘${RESET} Skipping ${1/$PWD\//}"
        fi
      fi
    else
      link_file "$1" "$2"
    fi
  fi
}

install_files() {
  for file in $@; do
    install_file "$PWD/$file" "$HOME/.$file"
  done
}

echo ""
echo "======================================"
echo "    Alright, let's dot those files    "
echo "======================================"

# ====================================
# Step 1: Initialize submodules
# ====================================
echo "Initializing and updating submodules (this may take some time)..."
if git submodule update --init --recursive; then
  echo -e "${FG_GREEN}✔${RESET} Initialised submodules"
else
  echo -e "${FG_RED}✘${RESET} Failed to initialise submodules"
fi

# ====================================
# Step 2: Install ZSH
# ====================================

echo ""
if ask "Would you like to install ${FG_BLUE}zsh${RESET} configs?"; then
  install_files zshrc zshenv zpreztorc zprezto
  install_file "$PWD/prezto_theme" "$PWD/zprezto/modules/prompt/functions/prompt_adam_setup"

  zsh=$(which zsh)
  if [ ! "$zsh" == "$SHELL" ]; then
    chsh -s "$(which zsh)"
  fi

  echo ""
fi

# ====================================
# Step 3: Install tmux
# ====================================

if ask "Would you like to install ${FG_BLUE}tmux${RESET} configs?"; then
  install_files "tmux.conf"
  echo ""
fi

# ====================================
# Step 4: Install git
# ====================================

if ask "Would you like to install ${FG_BLUE}git${RESET} configs?"; then
  install_files githelpers gitconfig
  echo ""
fi

# ====================================
# Step 5: Install Ruby (gemrc)
# ====================================

if ask "Would you like to install ${FG_BLUE}ruby${RESET} configs?"; then
  install_files gemrc
  echo ""
fi

# ====================================
# Step 6: Install vim
# ====================================

if ask "Would you like to install ${FG_BLUE}vim${RESET} configs?"; then
  install_files vimrc vim
  vim +PluginInstall +qall
fi

# ====================================
# Step 7: Set OS X defaults
# ====================================

if ask "Would you like to set some reasonble ${FG_BLUE}OS X${RESET} defaults?"; then
  sh osx 1>/dev/null
fi

echo ""
echo -e "${FG_GREEN}✔${RESET} All done! You may need to log out and back in to see all changes."
